# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: CI - Build

on:
  push:
    branches: [ master, "2.1"]
  pull_request:
    branches: [ master, "2.1" ]

jobs:
  test:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        ruby-version: [2.6.6, 2.5.8]
        
    steps:
    - uses: actions/checkout@v2
    - name: Prepare MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: 'myapp_test'
        mysql user: 'github'
    - name: Initialize MySQL for HackathonManager
      run: |
          mysql -u root -e "GRANT ALL PRIVILEGES ON myapp_test.* TO 'github'@'%';"
          mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
          export DATABASE_URL="mysql2://travis@localhost/myapp_test"
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@21351ecc0a7c196081abca5dc55b08f085efe09a
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install dependencies
      run: bundle install
    - name: Prepare database
      run: bin/rails db:migrate
    - name: Run tests
      run: bundle exec rake
